server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root
          url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&generateSimpleParameterMetadata=true
          hikari:
            max-pool-size: 20
            is-read-only: false
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root
          url: jdbc:mysql://127.0.0.1:3306/test_s1?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&generateSimpleParameterMetadata=true
          hikari:
            max-pool-size: 20
            is-read-only: true

mybatis-plus:
  mapper-locations: classpath*:xml/*.xml